services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: csv_dump
      MYSQL_MAX_ALLOWED_PACKET: 2G
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_general_ci
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  flask:
    build: .
    container_name: flask_app
    environment:
      DB_HOST: mariadb
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_PORT: 3306
      DB_NAME: csv_dump
      MONGO_HOST: mongodb
      MONGO_USER: root
      MONGO_PASSWORD: rootpassword
      MONGO_PORT: 27017
      MONGO_DB_NAME: csv_dump
    ports:
      - "5000:5000"
    depends_on:
      - mariadb
      - mongodb
    develop:
      watch:
        # Sync changes from the host to the container
        - action: sync
          path: ./flask_app
          target: /app
          ignore:
            - __pycache__/   # Example: Ignore Python bytecode files
        # Watch app.py specifically for changes
        - action: sync
          path: ./flask_app/app.py
          target: /app/app.py
        # Rebuild when requirements file changes (if you have one)
        - action: rebuild
          path: requirements.txt

volumes:
  mariadb_data:
    driver: local
  mongodb_data:
    driver: local
